services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:8.3
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=api
      - MYSQL_ROOT_PASSWORD=root
