services:
  api:
    build: api
    container_name: laravel_api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/var/www/html
      - ./api/vendor:/var/www/html/vendor
    command: bash -c "composer install && php artisan serve --host=0.0.0.0 --port=8000"
    depends_on:
      - db
  frontend:
    build: frontend
    container_name: nextjs_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api
  db:
    image: mysql:8.3
    ports:
      - "3306:3306"
    volumes:
      - ./api/docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=api
      - MYSQL_ROOT_PASSWORD=root